rctc:
  image: docker-registry.etnetera.cz/jahor/javatomcat-rctc:latest
  expose:
    - 8080
  environment:
    - JAVA=1.8.0
    - TOMCAT=7.0
  links:
    - db:db
  volumes_from:
    - jnpsnap1
    - jnpapp
  labels:
    io.rancher.sidekicks: jnpsnap1, jnpapp
db:
  image: mysql
  volumes_from:
    - jnpsnap2
  labels:
    io.rancher.sidekicks: jnpsnap2
  environment:
    - MYSQL_DATABASE=jnp_ng_demo
    - MYSQL_USER=jnp_ng_demo
    - MYSQL_PASSWORD=jnp_ng_demo
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - JNP_DOMAIN=jnpdemo-test.etnetera.cz
jnpsnap1:
  image: docker-registry.etnetera.cz/jahor/jnpng-data-snap
jnpsnap2:
  image: docker-registry.etnetera.cz/jahor/jnpng-data-snap
jnpapp:
  image: docker-registry.etnetera.cz/jahor/jnpng-app
